# ##############################################################################
# WORKFLOW
# ##############################################################################

# ------------------------------------------------------------------------------
# METADATA
# ------------------------------------------------------------------------------

#
# GENERAL
#

name: Pipeline

#
# TRIGGER
#

on:
  pull_request:
  push:
    tags:
      - "v*"
  workflow_dispatch:

# ##############################################################################
# ENVIRONMENT VARIABLES
# ##############################################################################

env:
  PROJECT_DOCKER_EXTRA_ARGS: ${{ vars.PROJECT_DOCKER_EXTRA_ARGS }}

# ##############################################################################
# JOBS
# ##############################################################################

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Prepare
        uses: schubergphilis/prepare-action@68aa577339a0a7307c3c9c4d9141a9b632e1fff8  # v1.0.0
        with:
          type: container
          job: lint

      - name: Load Environment Variables
        run: |
          direnv allow .
          direnv export gha > "$GITHUB_ENV"

      - name: Lint
        run: |
          task lint

  scan:
    name: Scan
    runs-on: ubuntu-24.04-arm
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Prepare
        uses: schubergphilis/prepare-action@68aa577339a0a7307c3c9c4d9141a9b632e1fff8  # v1.0.0
        with:
          type: container
          job: scan

      - name: Load Environment Variables
        run: |
          direnv allow .
          direnv export gha > "$GITHUB_ENV"

      - name: Scan
        run: |
          task scan

  ci-arm:
    name: CI (arm64)
    runs-on: ubuntu-24.04-arm
    needs: scan
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Prepare
        uses: schubergphilis/prepare-action@68aa577339a0a7307c3c9c4d9141a9b632e1fff8  # v1.0.0
        with:
          type: container
          job: ci

      - name: Load Environment Variables
        run: |
          direnv allow .
          direnv export gha > "$GITHUB_ENV"

      - name: Build
        env:
          PROJECT_DOCKER_PLATFORMS: linux/arm64
        run: |
          task build

      - name: Test
        env:
          PROJECT_DOCKER_PLATFORMS: linux/arm64
        run: |
          task test

  ci-amd:
    name: CI (amd64)
    runs-on: ubuntu-24.04
    needs: scan
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Prepare
        uses: schubergphilis/prepare-action@68aa577339a0a7307c3c9c4d9141a9b632e1fff8  # v1.0.0
        with:
          type: container
          job: ci

      - name: Load Environment Variables
        run: |
          direnv allow .
          direnv export gha > "$GITHUB_ENV"

      - name: Build
        env:
          PROJECT_DOCKER_PLATFORMS: linux/amd64
        run: |
          task build

      - name: Test
        env:
          PROJECT_DOCKER_PLATFORMS: linux/amd64
        run: |
          task test

  cd:
    name: CD
    runs-on: ubuntu-24.04-arm
    needs: [ci-amd, ci-arm]
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Prepare
        uses: schubergphilis/prepare-action@68aa577339a0a7307c3c9c4d9141a9b632e1fff8  # v1.0.0
        with:
          type: container
          job: cd

      - name: Load Environment Variables
        run: |
          direnv allow .
          direnv export gha > "$GITHUB_ENV"

      - name: Login to GitHub Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121  # v4.1.0
        with:
          registry: ${{ vars.PROJECT_DOCKER_HOST }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        run: |
          task release
